name: Deploy snapshots to self

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      OUTLINE_INSTANCE_URL:
        required: true
      OUTLINE_API_KEY:
        required: true
      OUTPUT_REPO_URL:
        required: true

jobs:
  deploy_snapshots_to_self:
    runs-on: ubuntu-latest
    container: ghcr.io/zensharp/outline-snapshot:latest
    steps:
      - name: Generate snapshots
        run: outline-snapshot
      - name: Deploy snapshot (Markdown)
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: mirror/markdown
          FOLDER: export-markdown
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy snapshot (JSON)
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: mirror/json
          FOLDER: export-json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}